services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 11090806
      MYSQL_DATABASE: mifica
      MYSQL_USER: mifica
      MYSQL_PASSWORD: 11090806
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mifica-backend:
    build: ./mifica-backend
    depends_on:
      - mysql
      - redis
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_REDIS_PASSWORD: ${ADMIN_REDIS_PASSWORD}
      CORS_ALLOWED_ORIGIN_PATTERNS: ${CORS_ALLOWED_ORIGIN_PATTERNS}
      MYSQLHOST: mysql
      MYSQLPORT: 3306
      MYSQLDATABASE: mifica
      MYSQLUSER: mifica
      MYSQLPASSWORD: 11090806
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_SSL: false
      BACKEND_PUBLIC_URL: http://localhost:8080
    volumes:
      - ~/.m2:/root/.m2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

  mifica-frontend:
    build: ./mifica-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  mifica-streamlit:
    build: ./mifica-streamlit
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit.rule=PathPrefix(`/streamlit`)"
      - "traefik.http.services.streamlit.loadbalancer.server.port=8501"
      - "traefik.http.routers.streamlit.entrypoints=web"
    command: >
      streamlit run app.py
      --server.baseUrlPath=streamlit
      --server.enableCORS=false
      --server.enableXsrfProtection=false

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data


volumes:
  mysql_data:
  redis_data:
