sonar.projectKey=mifica
sonar.projectName=Mifica
sonar.projectVersion=1.0

sonar.sources=mifica-backend/src/main,mifica-frontend/src,mifica-streamlit
sonar.tests=mifica-backend/src/test
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/.venv/**,**/__pycache__/**,**/*.min.js,**/coverage/**,**/docs/**,**/certbot/**,**/k8s/**

sonar.java.binaries=mifica-backend/target/classes
