apiVersion: v1
kind: Secret
metadata:
  name: mifica-secret
  namespace: mifica
type: Opaque
stringData:
  JWT_SECRET: "DGZBgzxxvHQBzat0cHcvS6vxSAy+UzHILpyYmFtCC4yYhFgtv+tj6fpLuSyq2iDASPaYbxSeh0OEfJXm8B0abw=="
  ADMIN_PASSWORD: "AdminSenha2026!"
  ADMIN_REDIS_PASSWORD: "Redis2026!"

  MYSQLUSER: "adminmifica"
  MYSQLPASSWORD: "Gab167118201!"
  MYSQL_ROOT_PASSWORD: "Gab167118201!"

  REDIS_USERNAME: "default"
  REDIS_PASSWORD: "Af-gAAIncDJkODRlNjM3YmEwMjE0NDMwODVlNDZhOWE4YjllN2M3N3AyNjU0NDA"
