apiVersion: v1
kind: Secret
metadata:
  name: mifica-secret
  namespace: mifica
type: Opaque
stringData:
  JWT_SECRET: "troque-por-um-segredo-forte"
  ADMIN_PASSWORD: "troque-por-uma-senha-admin"
  ADMIN_REDIS_PASSWORD: "troque-por-uma-senha-admin-redis"

  MYSQLUSER: "mifica"
  MYSQLPASSWORD: "troque-por-uma-senha-mysql"
  MYSQL_ROOT_PASSWORD: "troque-por-uma-senha-root"

  REDIS_USERNAME: "default"
  REDIS_PASSWORD: "troque-por-uma-senha-redis"
