# Nome da aplicação
spring.application.name=mifica-backend

# JWT
jwt.secret=${JWT_SECRET}
app.security.dev-mode=true
admin.cadastro.senha=${ADMIN_PASSWORD}
app.cors.allowed-origin-patterns=*

# Banco de dados MySQL
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Faz o Spring Boot esperar e tentar novamente
spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connectionTimeout=30000

# Desabilita usuário padrão do Spring Security
spring.security.user.name=
spring.security.user.password=
spring.security.user.roles=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desabilitar conf auto usuario em memória
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Configuração para usar Kafka real nos testes
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.sasl.mechanism=${KAFKA_SASL_MECHANISM:PLAIN}
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME:admin}" password="${KAFKA_PASSWORD:admin}";
spring.kafka.consumer.group-id=test-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


# Senha especial admin Kafka
admin.kafka.senha=${ADMIN_KAFKA_PASSWORD}

management.endpoints.web.exposure.include=health,info,mappings