apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mifica
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: mifica
        - name: MYSQL_USER
          value: mifica
        - name: MYSQL_PASSWORD
          value: mifica123
        - name: MYSQL_ROOT_PASSWORD
          value: root123
